/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.mjs
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2019
* @license Apache-2.0
*/
import BSONDeserialise from "../../operations/BSONDeserialise";
import BSONSerialise from "../../operations/BSONSerialise";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.BSON = {
    "BSON deserialise": BSONDeserialise,
    "BSON serialise": BSONSerialise,
};

export default OpModules;
