/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.mjs
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2019
* @license Apache-2.0
*/
import DecodeText from "../../operations/DecodeText";
import EncodeText from "../../operations/EncodeText";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.CharEnc = {
    "Decode text": DecodeText,
    "Encode text": EncodeText,
};

export default OpModules;
