/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.mjs
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2019
* @license Apache-2.0
*/
import CSSBeautify from "../../operations/CSSBeautify";
import CSSMinify from "../../operations/CSSMinify";
import CSSSelector from "../../operations/CSSSelector";
import FromMessagePack from "../../operations/FromMessagePack";
import GenericCodeBeautify from "../../operations/GenericCodeBeautify";
import JPathExpression from "../../operations/JPathExpression";
import JSONBeautify from "../../operations/JSONBeautify";
import JSONMinify from "../../operations/JSONMinify";
import JavaScriptBeautify from "../../operations/JavaScriptBeautify";
import JavaScriptMinify from "../../operations/JavaScriptMinify";
import JavaScriptParser from "../../operations/JavaScriptParser";
import SQLBeautify from "../../operations/SQLBeautify";
import SQLMinify from "../../operations/SQLMinify";
import SyntaxHighlighter from "../../operations/SyntaxHighlighter";
import ToCamelCase from "../../operations/ToCamelCase";
import ToKebabCase from "../../operations/ToKebabCase";
import ToMessagePack from "../../operations/ToMessagePack";
import ToSnakeCase from "../../operations/ToSnakeCase";
import XMLBeautify from "../../operations/XMLBeautify";
import XMLMinify from "../../operations/XMLMinify";
import XPathExpression from "../../operations/XPathExpression";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Code = {
    "CSS Beautify": CSSBeautify,
    "CSS Minify": CSSMinify,
    "CSS selector": CSSSelector,
    "From MessagePack": FromMessagePack,
    "Generic Code Beautify": GenericCodeBeautify,
    "JPath expression": JPathExpression,
    "JSON Beautify": JSONBeautify,
    "JSON Minify": JSONMinify,
    "JavaScript Beautify": JavaScriptBeautify,
    "JavaScript Minify": JavaScriptMinify,
    "JavaScript Parser": JavaScriptParser,
    "SQL Beautify": SQLBeautify,
    "SQL Minify": SQLMinify,
    "Syntax highlighter": SyntaxHighlighter,
    "To Camel case": ToCamelCase,
    "To Kebab case": ToKebabCase,
    "To MessagePack": ToMessagePack,
    "To Snake case": ToSnakeCase,
    "XML Beautify": XMLBeautify,
    "XML Minify": XMLMinify,
    "XPath expression": XPathExpression,
};

export default OpModules;
