/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.mjs
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2019
* @license Apache-2.0
*/
import GenerateUUID from "../../operations/GenerateUUID";
import JWTDecode from "../../operations/JWTDecode";
import JWTSign from "../../operations/JWTSign";
import JWTVerify from "../../operations/JWTVerify";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Crypto = {
    "Generate UUID": GenerateUUID,
    "JWT Decode": JWTDecode,
    "JWT Sign": JWTSign,
    "JWT Verify": JWTVerify,
};

export default OpModules;
