/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.mjs
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2019
* @license Apache-2.0
*/
import ADD from "../../operations/ADD";
import AND from "../../operations/AND";
import AddLineNumbers from "../../operations/AddLineNumbers";
import BitShiftLeft from "../../operations/BitShiftLeft";
import BitShiftRight from "../../operations/BitShiftRight";
import CartesianProduct from "../../operations/CartesianProduct";
import ChangeIPFormat from "../../operations/ChangeIPFormat";
import ChiSquare from "../../operations/ChiSquare";
import Comment from "../../operations/Comment";
import ConditionalJump from "../../operations/ConditionalJump";
import ConvertArea from "../../operations/ConvertArea";
import ConvertDataUnits from "../../operations/ConvertDataUnits";
import ConvertDistance from "../../operations/ConvertDistance";
import ConvertMass from "../../operations/ConvertMass";
import ConvertSpeed from "../../operations/ConvertSpeed";
import CountOccurrences from "../../operations/CountOccurrences";
import DechunkHTTPResponse from "../../operations/DechunkHTTPResponse";
import DecodeNetBIOSName from "../../operations/DecodeNetBIOSName";
import DetectFileType from "../../operations/DetectFileType";
import Divide from "../../operations/Divide";
import DropBytes from "../../operations/DropBytes";
import EncodeNetBIOSName from "../../operations/EncodeNetBIOSName";
import Entropy from "../../operations/Entropy";
import EscapeString from "../../operations/EscapeString";
import EscapeUnicodeCharacters from "../../operations/EscapeUnicodeCharacters";
import ExpandAlphabetRange from "../../operations/ExpandAlphabetRange";
import Fork from "../../operations/Fork";
import FormatMACAddresses from "../../operations/FormatMACAddresses";
import FrequencyDistribution from "../../operations/FrequencyDistribution";
import FromBCD from "../../operations/FromBCD";
import FromBase from "../../operations/FromBase";
import FromBase32 from "../../operations/FromBase32";
import FromBase58 from "../../operations/FromBase58";
import FromBase64 from "../../operations/FromBase64";
import FromBase85 from "../../operations/FromBase85";
import FromBinary from "../../operations/FromBinary";
import FromBraille from "../../operations/FromBraille";
import FromCharcode from "../../operations/FromCharcode";
import FromDecimal from "../../operations/FromDecimal";
import FromHTMLEntity from "../../operations/FromHTMLEntity";
import FromHex from "../../operations/FromHex";
import FromHexContent from "../../operations/FromHexContent";
import FromHexdump from "../../operations/FromHexdump";
import FromMorseCode from "../../operations/FromMorseCode";
import FromOctal from "../../operations/FromOctal";
import FromQuotedPrintable from "../../operations/FromQuotedPrintable";
import FromUNIXTimestamp from "../../operations/FromUNIXTimestamp";
import GenerateHOTP from "../../operations/GenerateHOTP";
import GenerateTOTP from "../../operations/GenerateTOTP";
import HTTPRequest from "../../operations/HTTPRequest";
import HammingDistance from "../../operations/HammingDistance";
import HaversineDistance from "../../operations/HaversineDistance";
import Head from "../../operations/Head";
import Jump from "../../operations/Jump";
import Label from "../../operations/Label";
import Magic from "../../operations/Magic";
import Mean from "../../operations/Mean";
import Median from "../../operations/Median";
import Merge from "../../operations/Merge";
import MicrosoftScriptDecoder from "../../operations/MicrosoftScriptDecoder";
import Multiply from "../../operations/Multiply";
import NOT from "../../operations/NOT";
import Numberwang from "../../operations/Numberwang";
import OR from "../../operations/OR";
import OffsetChecker from "../../operations/OffsetChecker";
import PHPDeserialize from "../../operations/PHPDeserialize";
import PadLines from "../../operations/PadLines";
import ParseColourCode from "../../operations/ParseColourCode";
import ParseDateTime from "../../operations/ParseDateTime";
import ParseUNIXFilePermissions from "../../operations/ParseUNIXFilePermissions";
import PowerSet from "../../operations/PowerSet";
import ROT13 from "../../operations/ROT13";
import ROT47 from "../../operations/ROT47";
import RemoveLineNumbers from "../../operations/RemoveLineNumbers";
import RemoveNullBytes from "../../operations/RemoveNullBytes";
import RemoveWhitespace from "../../operations/RemoveWhitespace";
import Return from "../../operations/Return";
import Reverse from "../../operations/Reverse";
import RotateLeft from "../../operations/RotateLeft";
import RotateRight from "../../operations/RotateRight";
import SUB from "../../operations/SUB";
import ScanForEmbeddedFiles from "../../operations/ScanForEmbeddedFiles";
import SetDifference from "../../operations/SetDifference";
import SetIntersection from "../../operations/SetIntersection";
import SetUnion from "../../operations/SetUnion";
import ShowBase64Offsets from "../../operations/ShowBase64Offsets";
import Sleep from "../../operations/Sleep";
import Sort from "../../operations/Sort";
import Split from "../../operations/Split";
import StandardDeviation from "../../operations/StandardDeviation";
import StripHTMLTags from "../../operations/StripHTMLTags";
import StripHTTPHeaders from "../../operations/StripHTTPHeaders";
import Substitute from "../../operations/Substitute";
import Subtract from "../../operations/Subtract";
import Sum from "../../operations/Sum";
import SwapEndianness from "../../operations/SwapEndianness";
import SymmetricDifference from "../../operations/SymmetricDifference";
import Tail from "../../operations/Tail";
import TakeBytes from "../../operations/TakeBytes";
import ToBCD from "../../operations/ToBCD";
import ToBase from "../../operations/ToBase";
import ToBase32 from "../../operations/ToBase32";
import ToBase58 from "../../operations/ToBase58";
import ToBase64 from "../../operations/ToBase64";
import ToBase85 from "../../operations/ToBase85";
import ToBinary from "../../operations/ToBinary";
import ToBraille from "../../operations/ToBraille";
import ToCharcode from "../../operations/ToCharcode";
import ToDecimal from "../../operations/ToDecimal";
import ToHTMLEntity from "../../operations/ToHTMLEntity";
import ToHex from "../../operations/ToHex";
import ToHexContent from "../../operations/ToHexContent";
import ToHexdump from "../../operations/ToHexdump";
import ToLowerCase from "../../operations/ToLowerCase";
import ToMorseCode from "../../operations/ToMorseCode";
import ToOctal from "../../operations/ToOctal";
import ToQuotedPrintable from "../../operations/ToQuotedPrintable";
import ToTable from "../../operations/ToTable";
import ToUNIXTimestamp from "../../operations/ToUNIXTimestamp";
import ToUpperCase from "../../operations/ToUpperCase";
import TranslateDateTimeFormat from "../../operations/TranslateDateTimeFormat";
import UNIXTimestampToWindowsFiletime from "../../operations/UNIXTimestampToWindowsFiletime";
import UnescapeString from "../../operations/UnescapeString";
import UnescapeUnicodeCharacters from "../../operations/UnescapeUnicodeCharacters";
import Unique from "../../operations/Unique";
import WindowsFiletimeToUNIXTimestamp from "../../operations/WindowsFiletimeToUNIXTimestamp";
import XKCDRandomNumber from "../../operations/XKCDRandomNumber";
import XOR from "../../operations/XOR";
import XORBruteForce from "../../operations/XORBruteForce";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Default = {
    "ADD": ADD,
    "AND": AND,
    "Add line numbers": AddLineNumbers,
    "Bit shift left": BitShiftLeft,
    "Bit shift right": BitShiftRight,
    "Cartesian Product": CartesianProduct,
    "Change IP format": ChangeIPFormat,
    "Chi Square": ChiSquare,
    "Comment": Comment,
    "Conditional Jump": ConditionalJump,
    "Convert area": ConvertArea,
    "Convert data units": ConvertDataUnits,
    "Convert distance": ConvertDistance,
    "Convert mass": ConvertMass,
    "Convert speed": ConvertSpeed,
    "Count occurrences": CountOccurrences,
    "Dechunk HTTP response": DechunkHTTPResponse,
    "Decode NetBIOS Name": DecodeNetBIOSName,
    "Detect File Type": DetectFileType,
    "Divide": Divide,
    "Drop bytes": DropBytes,
    "Encode NetBIOS Name": EncodeNetBIOSName,
    "Entropy": Entropy,
    "Escape string": EscapeString,
    "Escape Unicode Characters": EscapeUnicodeCharacters,
    "Expand alphabet range": ExpandAlphabetRange,
    "Fork": Fork,
    "Format MAC addresses": FormatMACAddresses,
    "Frequency distribution": FrequencyDistribution,
    "From BCD": FromBCD,
    "From Base": FromBase,
    "From Base32": FromBase32,
    "From Base58": FromBase58,
    "From Base64": FromBase64,
    "From Base85": FromBase85,
    "From Binary": FromBinary,
    "From Braille": FromBraille,
    "From Charcode": FromCharcode,
    "From Decimal": FromDecimal,
    "From HTML Entity": FromHTMLEntity,
    "From Hex": FromHex,
    "From Hex Content": FromHexContent,
    "From Hexdump": FromHexdump,
    "From Morse Code": FromMorseCode,
    "From Octal": FromOctal,
    "From Quoted Printable": FromQuotedPrintable,
    "From UNIX Timestamp": FromUNIXTimestamp,
    "Generate HOTP": GenerateHOTP,
    "Generate TOTP": GenerateTOTP,
    "HTTP request": HTTPRequest,
    "Hamming Distance": HammingDistance,
    "Haversine distance": HaversineDistance,
    "Head": Head,
    "Jump": Jump,
    "Label": Label,
    "Magic": Magic,
    "Mean": Mean,
    "Median": Median,
    "Merge": Merge,
    "Microsoft Script Decoder": MicrosoftScriptDecoder,
    "Multiply": Multiply,
    "NOT": NOT,
    "Numberwang": Numberwang,
    "OR": OR,
    "Offset checker": OffsetChecker,
    "PHP Deserialize": PHPDeserialize,
    "Pad lines": PadLines,
    "Parse colour code": ParseColourCode,
    "Parse DateTime": ParseDateTime,
    "Parse UNIX file permissions": ParseUNIXFilePermissions,
    "Power Set": PowerSet,
    "ROT13": ROT13,
    "ROT47": ROT47,
    "Remove line numbers": RemoveLineNumbers,
    "Remove null bytes": RemoveNullBytes,
    "Remove whitespace": RemoveWhitespace,
    "Return": Return,
    "Reverse": Reverse,
    "Rotate left": RotateLeft,
    "Rotate right": RotateRight,
    "SUB": SUB,
    "Scan for Embedded Files": ScanForEmbeddedFiles,
    "Set Difference": SetDifference,
    "Set Intersection": SetIntersection,
    "Set Union": SetUnion,
    "Show Base64 offsets": ShowBase64Offsets,
    "Sleep": Sleep,
    "Sort": Sort,
    "Split": Split,
    "Standard Deviation": StandardDeviation,
    "Strip HTML tags": StripHTMLTags,
    "Strip HTTP headers": StripHTTPHeaders,
    "Substitute": Substitute,
    "Subtract": Subtract,
    "Sum": Sum,
    "Swap endianness": SwapEndianness,
    "Symmetric Difference": SymmetricDifference,
    "Tail": Tail,
    "Take bytes": TakeBytes,
    "To BCD": ToBCD,
    "To Base": ToBase,
    "To Base32": ToBase32,
    "To Base58": ToBase58,
    "To Base64": ToBase64,
    "To Base85": ToBase85,
    "To Binary": ToBinary,
    "To Braille": ToBraille,
    "To Charcode": ToCharcode,
    "To Decimal": ToDecimal,
    "To HTML Entity": ToHTMLEntity,
    "To Hex": ToHex,
    "To Hex Content": ToHexContent,
    "To Hexdump": ToHexdump,
    "To Lower case": ToLowerCase,
    "To Morse Code": ToMorseCode,
    "To Octal": ToOctal,
    "To Quoted Printable": ToQuotedPrintable,
    "To Table": ToTable,
    "To UNIX Timestamp": ToUNIXTimestamp,
    "To Upper case": ToUpperCase,
    "Translate DateTime Format": TranslateDateTimeFormat,
    "UNIX Timestamp to Windows Filetime": UNIXTimestampToWindowsFiletime,
    "Unescape string": UnescapeString,
    "Unescape Unicode Characters": UnescapeUnicodeCharacters,
    "Unique": Unique,
    "Windows Filetime to UNIX Timestamp": WindowsFiletimeToUNIXTimestamp,
    "XKCD Random Number": XKCDRandomNumber,
    "XOR": XOR,
    "XOR Brute Force": XORBruteForce,
};

export default OpModules;
