/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.mjs
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2019
* @license Apache-2.0
*/
import FromPunycode from "../../operations/FromPunycode";
import ToPunycode from "../../operations/ToPunycode";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Encodings = {
    "From Punycode": FromPunycode,
    "To Punycode": ToPunycode,
};

export default OpModules;
