/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.mjs
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2019
* @license Apache-2.0
*/
import ExtractEXIF from "../../operations/ExtractEXIF";
import RemoveEXIF from "../../operations/RemoveEXIF";
import RenderImage from "../../operations/RenderImage";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Image = {
    "Extract EXIF": ExtractEXIF,
    "Remove EXIF": RemoveEXIF,
    "Render Image": RenderImage,
};

export default OpModules;
