/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.mjs
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2019
* @license Apache-2.0
*/
import GroupIPAddresses from "../../operations/GroupIPAddresses";
import ParseIPRange from "../../operations/ParseIPRange";
import ParseIPv4Header from "../../operations/ParseIPv4Header";
import ParseIPv6Address from "../../operations/ParseIPv6Address";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.JSBN = {
    "Group IP addresses": GroupIPAddresses,
    "Parse IP range": ParseIPRange,
    "Parse IPv4 header": ParseIPv4Header,
    "Parse IPv6 address": ParseIPv6Address,
};

export default OpModules;
