/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.mjs
*
* Imports all modules for builds which do not load modules separately.
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2019
* @license Apache-2.0
*/
import DefaultModule from "./Default";
import CiphersModule from "./Ciphers";
import LiberPrimusModule from "./LiberPrimus";
import HashingModule from "./Hashing";
import BSONModule from "./BSON";
import CompressionModule from "./Compression";
import CodeModule from "./Code";
import CharEncModule from "./CharEnc";
import DiffModule from "./Diff";
import ShellcodeModule from "./Shellcode";
import RegexModule from "./Regex";
import ImageModule from "./Image";
import EncodingsModule from "./Encodings";
import PGPModule from "./PGP";
import CryptoModule from "./Crypto";
import JSBNModule from "./JSBN";
import PublicKeyModule from "./PublicKey";
import URLModule from "./URL";
import UserAgentModule from "./UserAgent";

const OpModules = {};

Object.assign(
    OpModules,
    DefaultModule,
    CiphersModule,
    LiberPrimusModule,
    HashingModule,
    BSONModule,
    CompressionModule,
    CodeModule,
    CharEncModule,
    DiffModule,
    ShellcodeModule,
    RegexModule,
    ImageModule,
    EncodingsModule,
    PGPModule,
    CryptoModule,
    JSBNModule,
    PublicKeyModule,
    URLModule,
    UserAgentModule,
);

export default OpModules;
