/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.mjs
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2019
* @license Apache-2.0
*/
import GeneratePGPKeyPair from "../../operations/GeneratePGPKeyPair";
import PGPDecrypt from "../../operations/PGPDecrypt";
import PGPDecryptAndVerify from "../../operations/PGPDecryptAndVerify";
import PGPEncrypt from "../../operations/PGPEncrypt";
import PGPEncryptAndSign from "../../operations/PGPEncryptAndSign";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.PGP = {
    "Generate PGP Key Pair": GeneratePGPKeyPair,
    "PGP Decrypt": PGPDecrypt,
    "PGP Decrypt and Verify": PGPDecryptAndVerify,
    "PGP Encrypt": PGPEncrypt,
    "PGP Encrypt and Sign": PGPEncryptAndSign,
};

export default OpModules;
