/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.mjs
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2019
* @license Apache-2.0
*/
import HexToObjectIdentifier from "../../operations/HexToObjectIdentifier";
import HexToPEM from "../../operations/HexToPEM";
import ObjectIdentifierToHex from "../../operations/ObjectIdentifierToHex";
import PEMToHex from "../../operations/PEMToHex";
import ParseASN1HexString from "../../operations/ParseASN1HexString";
import ParseX509Certificate from "../../operations/ParseX509Certificate";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.PublicKey = {
    "Hex to Object Identifier": HexToObjectIdentifier,
    "Hex to PEM": HexToPEM,
    "Object Identifier to Hex": ObjectIdentifierToHex,
    "PEM to Hex": PEMToHex,
    "Parse ASN.1 hex string": ParseASN1HexString,
    "Parse X.509 certificate": ParseX509Certificate,
};

export default OpModules;
