/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.mjs
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2019
* @license Apache-2.0
*/
import ExtractDates from "../../operations/ExtractDates";
import ExtractDomains from "../../operations/ExtractDomains";
import ExtractEmailAddresses from "../../operations/ExtractEmailAddresses";
import ExtractFilePaths from "../../operations/ExtractFilePaths";
import ExtractIPAddresses from "../../operations/ExtractIPAddresses";
import ExtractMACAddresses from "../../operations/ExtractMACAddresses";
import ExtractURLs from "../../operations/ExtractURLs";
import Filter from "../../operations/Filter";
import FindReplace from "../../operations/FindReplace";
import Register from "../../operations/Register";
import RegularExpression from "../../operations/RegularExpression";
import Strings from "../../operations/Strings";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Regex = {
    "Extract dates": ExtractDates,
    "Extract domains": ExtractDomains,
    "Extract email addresses": ExtractEmailAddresses,
    "Extract file paths": ExtractFilePaths,
    "Extract IP addresses": ExtractIPAddresses,
    "Extract MAC addresses": ExtractMACAddresses,
    "Extract URLs": ExtractURLs,
    "Filter": Filter,
    "Find / Replace": FindReplace,
    "Register": Register,
    "Regular expression": RegularExpression,
    "Strings": Strings,
};

export default OpModules;
