/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.mjs
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2019
* @license Apache-2.0
*/
import ParseURI from "../../operations/ParseURI";
import URLDecode from "../../operations/URLDecode";
import URLEncode from "../../operations/URLEncode";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.URL = {
    "Parse URI": ParseURI,
    "URL Decode": URLDecode,
    "URL Encode": URLEncode,
};

export default OpModules;
